"""Add lieuDepart as part of primary key

Revision ID: 2fd7cafc4e37
Revises: c04afbc1f07d
Create Date: 2024-12-20 13:16:42.050600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd7cafc4e37'
down_revision: Union[str, None] = 'c04afbc1f07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preferences', 'lieuDepart',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preferences', 'lieuDepart',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
