"""Added autoincrement to id in Preferences

Revision ID: 4d17aebdfd8d
Revises: 2fd7cafc4e37
Create Date: 2024-12-20 13:34:44.519203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d17aebdfd8d'
down_revision: Union[str, None] = '2fd7cafc4e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_preferences_id', table_name='preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_preferences_id', 'preferences', ['id'], unique=False)
    # ### end Alembic commands ###
