"""Modification de la table preferences

Revision ID: c04afbc1f07d
Revises: 
Create Date: 2024-12-20 02:31:43.224198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04afbc1f07d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('dateDepart', sa.Date(), nullable=True))
    op.add_column('preferences', sa.Column('dateRetour', sa.Date(), nullable=True))
    op.drop_column('preferences', 'dateCreation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('dateCreation', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('preferences', 'dateRetour')
    op.drop_column('preferences', 'dateDepart')
    # ### end Alembic commands ###
